name: Deploy
on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        run: |
          cd /home/gshorti/src/gamification-platform
          git pull
          docker compose build
          docker compose up -d

